### ISSUE TITLE
Row height doesn't adjust after font size was changed

### ISSUE THREAD

**Issue by fpaaske** [nativescript-community/ui-collectionview#87]
### Which platform(s) does your issue occur on?
- iOS 18.1 emulator

### Please, provide the following version numbers that your issue occurs with:

npx nativescript-envinfo

```yaml
OS: macOS 15.1.1
CPU: (12) arm64 Apple M2 Pro
Shell: /bin/zsh
node: 20.14.0
npm: 10.7.0
nativescript: 8.7.2

# android
java: 11.0.18
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 16.1/16B40
cocoapods: 1.15.2
python: Not Found
python3: 3.13.0
ruby: 2.7.8
platforms:
  - DriverKit 24.1
  - iOS 18.1
  - macOS 15.1
  - tvOS 18.1
  - visionOS 2.1
  - watchOS 11.1
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~18.0.0",
  "@angular/common": "~18.0.0",
  "@angular/compiler": "~18.0.0",
  "@angular/core": "~18.0.0",
  "@angular/forms": "~18.0.0",
  "@angular/platform-browser": "~18.0.0",
  "@angular/platform-browser-dynamic": "~18.0.0",
  "@angular/router": "~18.0.0",
  "@nativescript-community/ui-collectionview": "^6.0.2",
  "@nativescript/angular": "^18.0.0",
  "@nativescript/core": "~8.8.0",
  "@nativescript/theme": "^3.1.0",
  "rxjs": "~7.8.0",
  "zone.js": "~0.14.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~18.0.0",
  "@angular/compiler-cli": "~18.0.0",
  "@nativescript/android": "8.7.2",
  "@nativescript/ios": "8.7.2",
  "@nativescript/types": "~8.8.0",
  "@nativescript/webpack": "~5.0.0",
  "@ngtools/webpack": "~18.0.0",
  "typescript": "~5.4.0"
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 

1. Create a new app, I used Angular template (**ns create ns-ng-cv-test --ng**)
2. Install the CollectionView plugin (**npm i @nativescript-community/ui-collectionview**)
3. Add css to enable a11y (**app.css**)
4. Replace ListView with CollectionView (**items.component.html**)
5. Run the app (**ns run ios**)
6. Put the app in the background (**swipe up**)
7. Open Settings -> Accessibility -> Display & Text Size -> Larger Text ->  Adjust slider
8. Resume app (**double tap home, select the app**)
9. Observe that the font size has changed (🤩), but the row height remains unchanged (😞)

**Before font change:**
<img width="551" alt="image" src="https://github.com/user-attachments/assets/d3162a96-006f-436a-ad84-d00d1ce4ac05">

**After font change:**
<img width="548" alt="image" src="https://github.com/user-attachments/assets/2d1ec56a-40a5-436e-b5cf-7e75ce2033df">

**If I kill the app and start it again, the row height is correct:**
<img width="549" alt="image" src="https://github.com/user-attachments/assets/0caaab5c-9a5b-4a07-a60f-98f4e0fdd341">

### Is there any code involved? 

```css
Label {
    font-size: 16;
    a11y-enabled: true;
    ios-accessibility-adjusts-font-size: true;
    ios-accessibility-max-font-scale: 5;
}
```

```html
<CollectionView [items]="items">
    <ng-template let-item="item">
        <GridLayout [nsRouterLink]="['/item', item.id]">
            <Label [text]="item.name"></Label>
        </GridLayout>
    </ng-template>
</CollectionView>
```
---

Side notes:

- ListView has similar problems, but seems to recover after interacting with it (scrolling intensely up and down?)
- ScrollView + for-loop works flawlessly, but can't be used due to performance issues with large lists.

- For Android, this seems to work as expected in all cases
